import Head from 'next/head'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* components  */}
      <Hero
        heading='Capture Photography'
        message='I capture moments in nature and keep them alive.'
      />

      <Slider slides={SliderData} />
    </div>
  )
}
